name: Docker Image CI

on:
  push:
    branches:
    - main
    - akritim-patch-1
    
jobs:

  build:
    runs-on: ubuntu-latest    
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
       username: akritimehta12
       password: ${{ secrets.DOCKER_TOKEN }}
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
