name: Docker Image CI

on:
  push:
    branches:
    - main
    - akritim-patch-1
    
jobs:

  build:
    runs-on: ubuntu-latest    
    
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
       username: akritimehta12
       password: ${{ secrets.DOCKER_TOKEN }}
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
       docker build . --file WebApp.Dockerfile --tag akritimehta12/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
       docker tag akritimehta12/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER akritimehta12/oai-embeddings:latest;
       docker push akritimehta12/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
       docker push akritimehta12/oai-embeddings:latest;
        
       docker build . --file BatchProcess.Dockerfile --tag akritimehta12/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
       docker tag akritimehta12/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER akritimehta12/oai-batch:latest;
       docker push akritimehta12/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
       docker push akritimehta12/oai-batch:latest;
